steps:
  integrationArtifactDeploy:
    cpiApiServiceKeyCredentialsId: CPISuite-Europe-09
    integrationFlowId: I050368-flow4
  integrationArtifactGetMplStatus:
    cpiApiServiceKeyCredentialsId: CPISuite-Europe-09
    integrationFlowId: I050368-flow4
  integrationArtifactUpload:
    cpiApiServiceKeyCredentialsId: CPISuite-Europe-09
    integrationFlowId: I050368-flow4
    integrationFlowName: I050368-flow4
    packageId: CICDDEMO
    filePath: I050368-flow4.zip
